import type { Business, Event, Leader } from "@/lib/supabase/types";

// Static data used when Supabase is not yet configured.
// Once connected, replace these with server-side Supabase queries.

export const businesses: Business[] = [
  {
    id: "1",
    name: "Broadway Biscuits",
    description: "Southern-style breakfast and brunch featuring locally sourced ingredients and homemade biscuits.",
    category: "Restaurant",
    address: "820 E Broadway, Louisville, KY 40204",
    phone: "(502) 555-0101",
    email: null,
    website: "https://broadwaybiscuits.example.com",
    image_url: null,
    latitude: 38.2395,
    longitude: -85.746,
    hours: "Mon-Sat 7am-2pm, Sun 8am-1pm",
    is_member: true,
    created_at: "",
  },
  {
    id: "2",
    name: "East Side Barber Co.",
    description: "Classic barbershop offering cuts, shaves, and grooming services in a vintage setting.",
    category: "Services",
    address: "844 E Broadway, Louisville, KY 40204",
    phone: "(502) 555-0102",
    email: null,
    website: null,
    image_url: null,
    latitude: 38.2393,
    longitude: -85.745,
    hours: "Tue-Sat 9am-6pm",
    is_member: true,
    created_at: "",
  },
  {
    id: "3",
    name: "Corridor Coffee",
    description: "Specialty coffee roaster and cafe with a focus on single-origin beans and community gathering.",
    category: "Coffee & Drinks",
    address: "900 E Broadway, Louisville, KY 40204",
    phone: "(502) 555-0103",
    email: null,
    website: "https://corridorcoffee.example.com",
    image_url: null,
    latitude: 38.239,
    longitude: -85.7435,
    hours: "Daily 6am-8pm",
    is_member: true,
    created_at: "",
  },
  {
    id: "4",
    name: "Broadway Blooms",
    description: "Full-service florist and plant shop specializing in local arrangements and urban gardening supplies.",
    category: "Retail",
    address: "870 E Broadway, Louisville, KY 40204",
    phone: "(502) 555-0104",
    email: null,
    website: null,
    image_url: null,
    latitude: 38.2392,
    longitude: -85.7445,
    hours: "Mon-Fri 9am-6pm, Sat 10am-4pm",
    is_member: true,
    created_at: "",
  },
  {
    id: "5",
    name: "Phoenix Gallery",
    description: "Contemporary art gallery showcasing Louisville artists with rotating exhibitions and community workshops.",
    category: "Arts & Culture",
    address: "932 E Broadway, Louisville, KY 40204",
    phone: "(502) 555-0105",
    email: null,
    website: "https://phoenixgallery.example.com",
    image_url: null,
    latitude: 38.2388,
    longitude: -85.7425,
    hours: "Wed-Sun 11am-7pm",
    is_member: true,
    created_at: "",
  },
  {
    id: "6",
    name: "Metro Legal Partners",
    description: "Full-service law firm specializing in small business, real estate, and community advocacy.",
    category: "Professional Services",
    address: "816 E Broadway, Louisville, KY 40204",
    phone: "(502) 555-0106",
    email: null,
    website: null,
    image_url: null,
    latitude: 38.2396,
    longitude: -85.7462,
    hours: "Mon-Fri 8am-5pm",
    is_member: true,
    created_at: "",
  },
  {
    id: "7",
    name: "The Broadway Tap",
    description: "Neighborhood bar and grill featuring Kentucky craft beers, bourbon flights, and live music.",
    category: "Restaurant",
    address: "960 E Broadway, Louisville, KY 40204",
    phone: "(502) 555-0107",
    email: null,
    website: "https://broadwaytap.example.com",
    image_url: null,
    latitude: 38.2386,
    longitude: -85.7415,
    hours: "Mon-Thu 4pm-12am, Fri-Sun 11am-2am",
    is_member: true,
    created_at: "",
  },
  {
    id: "8",
    name: "Baxter & Broadway Fitness",
    description: "Boutique fitness studio offering group classes, personal training, and wellness programs.",
    category: "Health & Wellness",
    address: "990 E Broadway, Louisville, KY 40204",
    phone: "(502) 555-0108",
    email: null,
    website: null,
    image_url: null,
    latitude: 38.2384,
    longitude: -85.7405,
    hours: "Mon-Fri 5am-9pm, Sat-Sun 7am-5pm",
    is_member: true,
    created_at: "",
  },
];

export const events: Event[] = [
  {
    id: "1",
    title: "Small Business Workshop: Digital Marketing 101",
    description: "Free workshop for corridor businesses on social media, Google Business profiles, and digital marketing basics.",
    date: "2026-04-10",
    end_date: null,
    time: "6:00 PM - 8:00 PM",
    location: "Metro Legal Partners, 816 E Broadway",
    category: "Workshop",
    image_url: null,
    is_approved: true,
    submitted_by: null,
    submitted_email: null,
    created_at: "",
  },
  {
    id: "2",
    title: "EBBA Monthly Meeting",
    description: "Open association meeting to discuss corridor improvements, upcoming events, and community input.",
    date: "2026-04-15",
    end_date: null,
    time: "7:00 PM - 8:30 PM",
    location: "Corridor Coffee, 900 E Broadway",
    category: "Meeting",
    image_url: null,
    is_approved: true,
    submitted_by: null,
    submitted_email: null,
    created_at: "",
  },
  {
    id: "3",
    title: "East Broadway Spring Market",
    description: "Outdoor market featuring local vendors, food trucks, live music, and family activities along the corridor.",
    date: "2026-04-19",
    end_date: null,
    time: "10:00 AM - 4:00 PM",
    location: "East Broadway Corridor",
    category: "Market",
    image_url: null,
    is_approved: true,
    submitted_by: null,
    submitted_email: null,
    created_at: "",
  },
  {
    id: "4",
    title: "Corridor Cleanup Day",
    description: "Community volunteer day to beautify the East Broadway corridor. Supplies provided.",
    date: "2026-04-26",
    end_date: null,
    time: "9:00 AM - 12:00 PM",
    location: "Meet at Corridor Coffee",
    category: "Volunteer",
    image_url: null,
    is_approved: true,
    submitted_by: null,
    submitted_email: null,
    created_at: "",
  },
  {
    id: "5",
    title: "First Friday Art Walk",
    description: "Monthly gallery walk featuring new exhibitions, artist meetups, and refreshments at corridor businesses.",
    date: "2026-05-01",
    end_date: null,
    time: "5:00 PM - 9:00 PM",
    location: "Phoenix Gallery & corridor businesses",
    category: "Arts & Culture",
    image_url: null,
    is_approved: true,
    submitted_by: null,
    submitted_email: null,
    created_at: "",
  },
  {
    id: "6",
    title: "Summer on Broadway Block Party",
    description: "Annual block party celebrating the East Broadway community with music, food, and activities.",
    date: "2026-06-14",
    end_date: null,
    time: "12:00 PM - 8:00 PM",
    location: "East Broadway (closed to traffic)",
    category: "Festival",
    image_url: null,
    is_approved: true,
    submitted_by: null,
    submitted_email: null,
    created_at: "",
  },
];

export const leaders: Leader[] = [
  {
    id: "1",
    name: "Marcus Thompson",
    title: "President",
    bio: "Marcus has owned Metro Legal Partners on East Broadway for 12 years and has been a driving force behind the association's reactivation. He is passionate about equitable development and supporting small businesses along the corridor.",
    image_url: null,
    email: "president@eastbroadwaylou.org",
    phone: null,
    order: 1,
    created_at: "",
  },
  {
    id: "2",
    name: "Angela Rivera",
    title: "Vice President",
    bio: "Angela is the founder of Broadway Blooms and a lifelong Louisville resident. She brings expertise in community organizing and a deep commitment to preserving the corridor's character while fostering growth.",
    image_url: null,
    email: "vp@eastbroadwaylou.org",
    phone: null,
    order: 2,
    created_at: "",
  },
  {
    id: "3",
    name: "David Chen",
    title: "Treasurer",
    bio: "David is a CPA and corridor business consultant who manages the association's finances. He helps member businesses with financial planning and tax strategy.",
    image_url: null,
    email: "treasurer@eastbroadwaylou.org",
    phone: null,
    order: 3,
    created_at: "",
  },
  {
    id: "4",
    name: "Lisa Washington",
    title: "Secretary",
    bio: "Lisa is a community activist and writer who has covered Louisville's neighborhoods for over a decade. She documents the association's progress and manages communications.",
    image_url: null,
    email: "secretary@eastbroadwaylou.org",
    phone: null,
    order: 4,
    created_at: "",
  },
  {
    id: "5",
    name: "James Okafor",
    title: "Events Coordinator",
    bio: "James brings 15 years of event planning experience and a talent for bringing people together. He coordinates all corridor events and manages partnerships with Louisville Metro.",
    image_url: null,
    email: "events@eastbroadwaylou.org",
    phone: null,
    order: 5,
    created_at: "",
  },
];
